[project]
name = "counter"
authors = []
description = "A simple counter on Stacks"
telemetry = false
requirements = []
[contracts.counter]
path = "contracts/counter.clar"
clarity_version = 3
epoch = 'latest'
